/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as WhyChooseUsRouteImport } from "./routes/why-choose-us";
import { Route as TestimonialsRouteImport } from "./routes/testimonials";
import { Route as TermsRouteImport } from "./routes/terms";
import { Route as SitemapDotxmlRouteImport } from "./routes/sitemap[.]xml";
import { Route as ServicesRouteImport } from "./routes/services";
import { Route as PrivacyRouteImport } from "./routes/privacy";
import { Route as PricingRouteImport } from "./routes/pricing";
import { Route as HowItWorksRouteImport } from "./routes/how-it-works";
import { Route as FaqRouteImport } from "./routes/faq";
import { Route as ContactRouteImport } from "./routes/contact";
import { Route as CareersRouteImport } from "./routes/careers";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as IndexRouteImport } from "./routes/index";

const WhyChooseUsRoute = WhyChooseUsRouteImport.update({
  id: "/why-choose-us",
  path: "/why-choose-us",
  getParentRoute: () => rootRouteImport,
});
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: "/testimonials",
  path: "/testimonials",
  getParentRoute: () => rootRouteImport,
});
const TermsRoute = TermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => rootRouteImport,
});
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: "/sitemap.xml",
  path: "/sitemap.xml",
  getParentRoute: () => rootRouteImport,
});
const ServicesRoute = ServicesRouteImport.update({
  id: "/services",
  path: "/services",
  getParentRoute: () => rootRouteImport,
});
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
});
const PricingRoute = PricingRouteImport.update({
  id: "/pricing",
  path: "/pricing",
  getParentRoute: () => rootRouteImport,
});
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: "/how-it-works",
  path: "/how-it-works",
  getParentRoute: () => rootRouteImport,
});
const FaqRoute = FaqRouteImport.update({
  id: "/faq",
  path: "/faq",
  getParentRoute: () => rootRouteImport,
});
const ContactRoute = ContactRouteImport.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => rootRouteImport,
});
const CareersRoute = CareersRouteImport.update({
  id: "/careers",
  path: "/careers",
  getParentRoute: () => rootRouteImport,
});
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  WhyChooseUsRoute: WhyChooseUsRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes();
